version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    command: bot
    restart: on-failure:5
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    command: worker
    restart: on-failure:5
    env_file:
      - .env
    depends_on:
      - rabbitmq

  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:management
    restart: unless-stopped

volumes:
  mongo-data:
